[package]
name = "comic-ocr-synth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
image.workspace = true
serde.workspace = true
serde_json.workspace = true
ab_glyph = "0.2"
imageproc = "0.25"
rand = "0.8"

[dev-dependencies]
comic-ocr-ort = { path = "../comic-ocr-ort" }
comic-ocr-core = { path = "../comic-ocr-core" }
